name: ${name}
version: ${version}
description: ${description}
main: io.multipaper.extras.MultiPaperExtras
api-version: '1.20'
folia-supported: true
depend: [ spark, UnifiedMetrics ]
authors: [ bystepii ]
